#!/usr/bin/perl 

use lib "$ENV{HOME}/lib/perl";
require "menu_subs.pl";
use Menu; 
use Getopt::Long;

my $delim = "\n";
my @choices = &init_choices();

GetOptions(
    'choice:s@'         => \@choices,
    'choices:s'          => sub {
        my ($name, $value) = @_;
        push(@choices, grep( /\S/, split($delim, $value)));
    },
    'default:s'         => \my $default,
    'pre:s'             => \my $pre,
    'post:s'            => \my $post,
    'output:s'          => \my $file,
    'delim:s'           => \$delim);

$menu = Menu->new;
$menu->type( 'multiple' );
$menu->default( $default ) if $default;
$menu->choices( @choices ) if scalar(@choices);
$menu->preMessage( $pre ) if $pre;
$menu->postMessage( $post ) if $post;
output($menu, $delim, $file);
