#!/bin/bash

for field in "Date/Time Original" "Create Date"; do
   folder=$(exiftool "$1" | grep -i "$field" | head -1 | cut -f2,3 -d: | sed "s/:/-/" | sed "s/ //")
   if [ ! -z "$folder" ]; then
      echo $folder
      exit 
   fi
done
