#!/bin/bash

BASE="../../"
source $BASE/functions

initialize $HOME/util/multisched
install_file $HOME/util/multisched runner

initialize $HOME/lib/multisched
install_file $HOME/lib/multisched multisched.bash 
install_file $HOME/lib/multisched settings.sh
