#!/bin/bash

SITE=$1
CELLGEN=`${HOME}/cadabraPath cellgen`
HOST=`${CELLGEN}/bin/machine -c all -s $SITE -1`
if [ -z "$HOST" ]; then
   HOST=$SITE
fi

DIRECTORY=P4workspace

LOCAL_DIRECTORY=${HOME}/$DIRECTORY
REMOTE_DIRECTORY=`rsh $HOST pwd`/$DIRECTORY

echo Updating Utilities from ${LOCAL_DIRECTORY} to $HOST:${REMOTE_DIRECTORY}

# Synchronize with the remote site
if [ -z "$USER" ]; then
   USER=`whoami`
fi
/depot/rsync/bin/rsync --rsync-path=/depot/rsync/bin/rsync --rsh="rsh -l $USER" --exclude='**~' --exclude='.p4config' -azvc ${LOCAL_DIRECTORY}/ $HOST:${REMOTE_DIRECTORY}
rsh $HOST updateUtil
