#!/bin/env perl

undef $/;
my $al = 0;
my $unwrap = 1;

while( <> ) {
  if ( $al ) {
    s|//.*||g;
  } else {
    s|#.*||g;
  }

  if ( $unwrap ) {
    if ( !$al ) {
      s|\\\n[ \t]+| |g;
    } else {
      s|([\(\=\,\&\|\*\+\-\/])[ \t]*\n[ \t]*(\S)|$1 $2|g;
      s|[ \t]*\n[ \t]*\&\&| &&|g;
      s/[ \t]*\n[ \t]*\|\|/ ||/g;
      s|\"[ \t]*\n[ \t]*\"|" "|g;
    }
  }
  s|[ \t]+\n|\n|g;
  s|\n{2,}|\n|g;
  s|^\s*||g;
  print $_;
}

