#!/bin/env perl

# -----------------------------------------------------------------------
# Process command line arguments
use Getopt::Long;
@optionList = ( "columns=s", "delimiter=s" );
GetOptions( @optionList );

# Delimiter
$delimiter = ',';
$delimiter = $opt_delimiter if ( $opt_delimiter );

# Column Numbers
@columns = ();
@columns = split( ',', $opt_columns ) if ( $opt_columns );

while( <STDIN> ) {
   @data = split( $delimiter );
   foreach $i ( @columns ) {
       $data[$i] = &toTime( $data[$i] );
   }
   print join( $delimiter, @data );
}

sub toTime {
   my $time = shift;
   return $time if ( $time == 0 && $time ne '0' && $time ); 
   my $hour = int($time/3600);
   $time = $time % 3600;
   my $minute = int($time/60);
   my $second = $time % 60; 
   #return sprintf( "%02d:%02d:%02d", ( localtime( $time ) )[0,1,2] );
   return sprintf( "%02d:%02d:%02d", $hour, $minute, $second );
}
