#!/bin/env perl

# First name mapping.
%firstName = (
'a', 'stinky',	
'b', 'lumpy',
'c', 'buttercup',
'd', 'gidget',
'e', 'crusty',
'f', 'greasy',
'g', 'fluffy',
'h', 'cheeseball',
'i', 'chim-chim',
'j', 'poopsie',
'k', 'flunky',
'l', 'booger',
'm', 'pinky',
'n', 'zippy',
'o', 'goober',
'p', 'doofus',
'q', 'slimy',
'r', 'loopy',
's', 'snotty',
't', 'falafel',
'u', 'dorkey',
'v', 'squeezit',
'w', 'oprah',
'x', 'skipper',
'y', 'dinky',
'z', 'zsa-zsa' );

# Last Name Mapping	
%lastName1 = (
'a', 'diaper',
'b', 'toilet',
'c', 'giggle',
'd', 'bubble',
'e', 'girdle',
'f', 'barf',
'g', 'lizard',
'h', 'waffle',
'i', 'cootie',
'j', 'monkey',
'k', 'potty',
'l', 'liver',
'm', 'banana',
'n', 'rhino',
'o', 'burger',
'p', 'hamster',
'q', 'toad',
'r', 'gizzard',
's', 'pizza',
't', 'gerbil',
'u', 'chicken',
'v', 'pickle',
'w', 'chuckle',
'x', 'tofu',
'y', 'gorilla',
'z', 'stinker' );

%lastName2 = ( 
'a', 'head',
'b', 'mouth',
'c', 'face',
'd', 'nose',
'e', 'tush',
'f', 'breath',
'g', 'pants',
'h', 'shorts',
'i', 'lips',
'j', 'honker',
'k', 'butt',
'l', 'brain',
'm', 'tushie',
'n', 'chunks',
'o', 'hiney',
'p', 'biscuits',
'q', 'toes',
'r', 'buns',
's', 'fanny',
't', 'sniffer',
'u', 'sprinkles',
'v', 'kisser',
'w', 'squirt',
'x', 'humperdinck',
'y', 'brains',
'z', 'juice' );

# Process the arguments.
$firstName = $ARGV[0];
$lastName = $ARGV[1];

# Convert the name.
$firstName =~ s/(.).*/\u$firstName{lc $1}/;
$lastName =~ s/(.)(.*(.))?/\u$lastName1{lc $1}$lastName2{lc $3}/;

printf( "%s %s\n", $firstName, $lastName );
