#!/bin/env perl

use Time::Local;

@Months = ( 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec' );

# Get the data.
$date = $ARGV[0];
$delta = $ARGV[1];

# Get the starting date info.
my ( $day, $month, $year, $hour, $minute, $second ) = ( $date =~ m|(\d{1,2})/(\d{1,2})/(\d{1,4})(\s+(\d{1,2}):(\d{1,2}):(\d{1,2}))?| )[0,1,2,4,5,6];
$month--;
$year -= 1900 if ( $year > 1000 );
my $startTime = timelocal( $second, $minute, $hour, $day, $month, $year );

my $finishTime = $startTime + $delta * ( 60 * 60 * 24 );

( $year, $month, $day, $hour, $minute, $second ) = ( localtime( $finishTime ) )[5,4,3,2,1,0];

printf( "%s %d, %d", $Months[$month], $day, $year+1900 );
if ( $date =~ /:/ ) {
  printf( " %02d:%02d:%02d", $hour, $minute, $second );
}
print "\n";
