#!/usr/bin/env python3

import json
import sys
import multisched

settings = multisched.settings()
value = sys.argv[2]
try:
    value = json.loads(value)
except:
    value

settings[sys.argv[1]] = value 
print(json.dumps(settings))

