#!/usr/bin/env python3

import os
import sys
sys.dont_write_bytecode = True

# External modules
sys.path.append(os.path.join(os.getenv('HOME'), 'lib', 'multisched'))
import manager

manager.distribute()
