#!/bin/bash
. ${HOME}/util/process/process.sh
process

. ${HOME}/util/sge/init.sh
jid=''
rhost=''
_qinit $1 jid rhost
if [ ! -z "$rhost" ]; then
   util=`basename $0`
   rsh $rhost $util $jid/${SGE_CELL}
   exit
fi

file=`qstat -j ${jid} | grep stdout_path_list | cut -f4 -d:`
echo "SGE Log File - ${file}"
tail -f $file
