#!/bin/bash

base=$(dirname $BASH_SOURCE)
. ${base}/space_utils.sh

space_args "${@}"

check_regressions /scratch/project
check_regressions /project
check_other Users /scratch/user
check_other Other /scratch
