#!/bin/bash

. $(dirname $BASH_SOURCE)/vnc_utils.sh

function isActive() {
 	local disp=$1
	local user=$2
	local num=0

	local proc=$(ps --user $user -f | grep "/usr/bin/Xtigervnc :${disp} " | grep -v grep)
	local port=$(vnc_get_port "$proc")
	if [ ! -z "$port" ]; then
		num=$(netstat -tulpn 2>/dev/null | grep LISTEN | grep ":${port}" | wc -l)
	fi

	[[ $num == 2 ]] && echo -e "\t(Active on port $port)" || echo ""
}

ROOTDIR=$(cd $HOME/.. && pwd)
echo -e "Display\t Userid"
ls $ROOTDIR/*/.vnc/$(hostname).*.log | sed 's|/|:|g' | sed 's/.log//' | cut -f3,6 -d: | awk -F ':' '{print($2,"\t",$1)}' | sort -k1 -n | while read line; do
	disp=$(echo $line | awk '{print $1}')
	user=$(echo $line | awk '{print $2}')
	echo "$line $(isActive $disp $user)" 
done
