#!/usr/bin/python3

import sys
import getopt
from teams import TeamsIdentity


if __name__ == "__main__":
    try:
        opts, args = getopt.getopt(
                sys.argv[1:], "n:",
                ["name"])
    except getopt.GetoptError as err:
        print(err)
        sys.exit(2)

    result = {}

    name = None
    for o, a in opts:
        if o in ('-n', 'name'):
            name = a

    ident = TeamsIdentity(name = name)
    print(ident.url())
