#!/bin/bash

#################################################################################
# kmail
# 
# Used to convert any given text content through STDIN using the kramdown
# markdown processing and then send as email to the desired recipients with a 
# HTML header so that it is rendered properly in the mail tool.
#
# Has all the same options as the mail tool.
#

hmail=$(dirname $BASH_SOURCE)/hmail
if [ -t 0 ]; then
    $hmail "${@}"
else
    kramdown -o html | $hmail "${@}"
fi
