#!/bin/bash

BASE="../../"
source $BASE/functions

initialize $HOME/lib/google
install_file $HOME/lib/google include.sh

initialize $HOME/util/google
install_file $HOME/util/google gtee
install_file $HOME/util/google todoc
install_other $HOME/util/google
