#!/bin/bash

argv=()
files=()
append=''

while [[ $# -gt 0 ]]
do
    case "$1" in
        -a|--append)
            append='-a'
            ;;
        -*)
            argv+=("$1")
            ;;
        *)
            files+=("$1")
    esac
    shift
done 

p=()
for f in "${files[@]}"
do
    d=$(dirname $f)
    exec {fd}> >(todoc -q -f $f $(if [ "$d" != "." ]; then echo "-p $d"; fi) ${append})
    p+=($fd)
done

cd /dev/fd && exec tee ${argv} "${p[@]}"
