#!/bin/bash

function old_tags() {
    grep -e '^v'
}

function new_tags() {
    grep -E '^[0-9]{8}\.[0-9]+\.[0-9]+' | \
    grep -v -E '[0-9]{9}'| \
    sort -t . -n -k1,1 -k2,2 -k3,3
}


git for-each-ref refs/tags | awk '{print $3}'| sed 's|refs/tags/||' | \
    tee >(new_tags) >(old_tags) >/dev/null
