#!/bin/bash

base=$(dirname $BASH_SOURCE)
if [[ $(${base}/git_is) == 0 ]]; then echo ""; exit; fi
branch=$(git branch | grep \* | cut -d ' ' -f2)
branch=$(if [ "$1" == "1" ]; then echo "\e[32m$branch\e[m"; else echo $branch; fi)
if [ -z "$branch" ]; then echo ""; else echo -e "$2[$branch]$3"; fi
