#!/usr/bin/python3

import os
import sys
import getopt
import project

try:
    opts, other = \
        getopt.getopt(sys.argv[1:],
                      "b:hn",
                      ("branch=", "help"))
except getopt.GetoptError as err:
    print(str(err))
    sys.exit(2)


def usage():
    program = os.path.basename(sys.argv[0])
    print("Usage: {} [-b/--branch <BRANCH>] ".format(program))
    print("Used to launch the build.\n")
    print("  -h, --help         Display this help information")
    print("  -b, --branch       The branch to create")
    print("  -n, --noopt        "
          "Perform no operation, just display the access URLs and arguments\n")
    print("Report bugs to: brian.hill@metrics.ca\n")


params = {'OS_NAME': 'debian_10',
          'DEPLOY': 'internal_shell',
          'DEPLOY_CLIENT': 'nightly',
          'DO_RELEASE': 0,
          'DO_SHUFFLE': 1}
branch = 'DEV'
preview = 0
for o, a in opts:
    if o in ('-h', '--help'):
        usage()
        sys.exit(0)

    if o in ('-b', '--branch'):
        branch = a

    if o in ('-n', '--noopt'):
        preview = 1

pipelines = project.Pipelines('dsim/source', preview=preview)
p = pipelines.launch(branch, params)
print("Submitted: {}".format(p.pipeline_id))
p.wait()
exit(0 if p.overallStatus() == "success" else 1)
